//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventLogging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlarmStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlarmStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventLogging.AlarmStrings", typeof(AlarmStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string AlarmOff {
            get {
                return ResourceManager.GetString("AlarmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string AlarmOn {
            get {
                return ResourceManager.GetString("AlarmOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder Deviation Alarm Level Reached {0} um Ch {1}.
        /// </summary>
        internal static string CylinderDeviationAlarmLevelReached {
            get {
                return ResourceManager.GetString("CylinderDeviationAlarmLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Monitor Cylinder Sum {0} um Cyl {1}.
        /// </summary>
        internal static string DamageMonitorCylinderSum {
            get {
                return ResourceManager.GetString("DamageMonitorCylinderSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Monitor Main Bearing Neighbour Sum {0} um MBN {1}.
        /// </summary>
        internal static string DamageMonitorMainBearingNeighbourSMBN {
            get {
                return ResourceManager.GetString("DamageMonitorMainBearingNeighbourSMBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Monitor Single Sensor {0} um Ch {1}.
        /// </summary>
        internal static string DamageMonitorSingleSensor {
            get {
                return ResourceManager.GetString("DamageMonitorSingleSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAM 1 Communications fault{0}{1}.
        /// </summary>
        internal static string FRAM1Communicationsfault {
            get {
                return ResourceManager.GetString("FRAM1Communicationsfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss of communications to SPU{0}{1}.
        /// </summary>
        internal static string LossofcommunicationstoSPU {
            get {
                return ResourceManager.GetString("LossofcommunicationstoSPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss of communications to TMP module.
        /// </summary>
        internal static string LossofcommunicationstoTMP {
            get {
                return ResourceManager.GetString("LossofcommunicationstoTMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time clock failure, time reset{0}{1}.
        /// </summary>
        internal static string Realtimeclockfailuretimereset {
            get {
                return ResourceManager.GetString("Realtimeclockfailuretimereset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Card Error{0}{1}.
        /// </summary>
        internal static string SDCardError {
            get {
                return ResourceManager.GetString("SDCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Alarm Deviation Level Reached {0} um Ch {1}.
        /// </summary>
        internal static string SensorAlarmDeviationLevelReached {
            get {
                return ResourceManager.GetString("SensorAlarmDeviationLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Alarm Level Reached {0} um Ch {1}.
        /// </summary>
        internal static string SensorAlarmLevelReached {
            get {
                return ResourceManager.GetString("SensorAlarmLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor failure High Ch {0}{1}.
        /// </summary>
        internal static string SensorfailureHigh {
            get {
                return ResourceManager.GetString("SensorfailureHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor failure Low Ch {0}{1}.
        /// </summary>
        internal static string SensorfailureLow {
            get {
                return ResourceManager.GetString("SensorfailureLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor failure No pulse on Ch {0}{1}.
        /// </summary>
        internal static string SensorfailureNopulse {
            get {
                return ResourceManager.GetString("SensorfailureNopulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor failure Unstable Ch {0}{1}.
        /// </summary>
        internal static string SensorfailureUnstable {
            get {
                return ResourceManager.GetString("SensorfailureUnstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Moved During Learning Ch {0}{1}.
        /// </summary>
        internal static string SensorMovedDuringLearning {
            get {
                return ResourceManager.GetString("SensorMovedDuringLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Pre-warning Level: {0} um Ch {1}.
        /// </summary>
        internal static string SensorPrewarningLevel {
            get {
                return ResourceManager.GetString("SensorPrewarningLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Slow Down Deviation Level Reached {0} um Ch {1}.
        /// </summary>
        internal static string SensorSlowDownDeviationLevelReached {
            get {
                return ResourceManager.GetString("SensorSlowDownDeviationLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Slow Down Level Reached {0} um Ch {1}.
        /// </summary>
        internal static string SensorSlowDownLevelReached {
            get {
                return ResourceManager.GetString("SensorSlowDownLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEDM Alarm Level Reached {0} mV{1}.
        /// </summary>
        internal static string SLEMAlarmLevelReachedmV {
            get {
                return ResourceManager.GetString("SLEMAlarmLevelReachedmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEDM Connection Failure input high{0}{1}.
        /// </summary>
        internal static string SLEMConnectionFailureinputhigh {
            get {
                return ResourceManager.GetString("SLEMConnectionFailureinputhigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEDM Connection Failure input low{0}{1}.
        /// </summary>
        internal static string SLEMConnectionFailureinputlow {
            get {
                return ResourceManager.GetString("SLEMConnectionFailureinputlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPU Clock Battery Low{0}{1}.
        /// </summary>
        internal static string SPUClockBatteryLow {
            get {
                return ResourceManager.GetString("SPUClockBatteryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Level Reached {0} °C in {1}.
        /// </summary>
        internal static string TemperatureAlarmLevelReached {
            get {
                return ResourceManager.GetString("TemperatureAlarmLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose connection in {0}.
        /// </summary>
        internal static string TemperatureAlarmLoseConnection {
            get {
                return ResourceManager.GetString("TemperatureAlarmLoseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTM module failure in {0}.
        /// </summary>
        internal static string TemperatureAlarmLosePower {
            get {
                return ResourceManager.GetString("TemperatureAlarmLosePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open circuit in {0}.
        /// </summary>
        internal static string TemperatureAlarmOpenCircuit {
            get {
                return ResourceManager.GetString("TemperatureAlarmOpenCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit in {0}.
        /// </summary>
        internal static string TemperatureAlarmShortCircuit {
            get {
                return ResourceManager.GetString("TemperatureAlarmShortCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Down Level Reached {0} °C in {1}.
        /// </summary>
        internal static string TemperatureSlowDownLevelReached {
            get {
                return ResourceManager.GetString("TemperatureSlowDownLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water in oil alarm level 1 {0} %{1}.
        /// </summary>
        internal static string Waterinoilalarmlevel1 {
            get {
                return ResourceManager.GetString("Waterinoilalarmlevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water in oil alarm level 2 {0} %{1}.
        /// </summary>
        internal static string Waterinoilalarmlevel2 {
            get {
                return ResourceManager.GetString("Waterinoilalarmlevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water in oil connection failure{0}{1}.
        /// </summary>
        internal static string Waterinoilconnectionfailure {
            get {
                return ResourceManager.GetString("Waterinoilconnectionfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water in oil connection failure input high{0}{1}.
        /// </summary>
        internal static string Waterinoilconnectionfailureinputhigh {
            get {
                return ResourceManager.GetString("Waterinoilconnectionfailureinputhigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water in oil connection failure input low{0}{1}.
        /// </summary>
        internal static string Waterinoilconnectionfailureinputlow {
            get {
                return ResourceManager.GetString("Waterinoilconnectionfailureinputlow", resourceCulture);
            }
        }
    }
}
