//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventLogging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventLogging.EventStrings", typeof(EventStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Test Mode Status Disabled - Normal Mode.
        /// </summary>
        internal static string AlarmTestModeStatusDisabledNormalMode {
            get {
                return ResourceManager.GetString("AlarmTestModeStatusDisabledNormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Test Mode Status Enabled - Test Mode.
        /// </summary>
        internal static string AlarmTestModeStatusEnabledTestMode {
            get {
                return ResourceManager.GetString("AlarmTestModeStatusEnabledTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPU Date and Time Changed.
        /// </summary>
        internal static string ChangeSpuTime {
            get {
                return ResourceManager.GetString("ChangeSpuTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm List Cleared.
        /// </summary>
        internal static string ClearAlarmList {
            get {
                return ResourceManager.GetString("ClearAlarmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing Order Cleared.
        /// </summary>
        internal static string ClearFiringOrder {
            get {
                return ResourceManager.GetString("ClearFiringOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Value Changed.
        /// </summary>
        internal static string Configurationvaluechanged {
            get {
                return ResourceManager.GetString("Configurationvaluechanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Version Upgrade to: {0}.
        /// </summary>
        internal static string CPUUpdate {
            get {
                return ResourceManager.GetString("CPUUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cr Offset Ch {0} old: {1} new: {2}.
        /// </summary>
        internal static string CrOffsetCh {
            get {
                return ResourceManager.GetString("CrOffsetCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Offset Ch {0} old: {1} new: {2}.
        /// </summary>
        internal static string DCOffsetCh {
            get {
                return ResourceManager.GetString("DCOffsetCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Learning Procedure Aborted By User.
        /// </summary>
        internal static string EngineLearningProcedureAbortedByUser {
            get {
                return ResourceManager.GetString("EngineLearningProcedureAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Learning Stage: Stage 1 Learning.
        /// </summary>
        internal static string EngineLearningStage1Learning {
            get {
                return ResourceManager.GetString("EngineLearningStage1Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Learning Stage: Stage 2 Learning.
        /// </summary>
        internal static string EngineLearningStage2Learning {
            get {
                return ResourceManager.GetString("EngineLearningStage2Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Learning Stage: Stage 3 Learning.
        /// </summary>
        internal static string EngineLearningStage3Learning {
            get {
                return ResourceManager.GetString("EngineLearningStage3Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Learning Stage: Engine Learning Completed.
        /// </summary>
        internal static string EngineLearningStageEngineLearningCompleted {
            get {
                return ResourceManager.GetString("EngineLearningStageEngineLearningCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Learning Stage: Fine Learning Started.
        /// </summary>
        internal static string EngineLearningStageFineLearningStarted {
            get {
                return ResourceManager.GetString("EngineLearningStageFineLearningStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log Cleared.
        /// </summary>
        internal static string EventLogCleared {
            get {
                return ResourceManager.GetString("EventLogCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing Order / Engine Direction Clearing Firing Order.
        /// </summary>
        internal static string FiringOrderEngineDirectionClearingFiringOrder {
            get {
                return ResourceManager.GetString("FiringOrderEngineDirectionClearingFiringOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing Order / Engine Direction Determing Order.
        /// </summary>
        internal static string FiringOrderEngineDirectionDetermingOrder {
            get {
                return ResourceManager.GetString("FiringOrderEngineDirectionDetermingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Engine Learning Initiated.
        /// </summary>
        internal static string FullEngineLearningInitiated {
            get {
                return ResourceManager.GetString("FullEngineLearningInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature settings imported.
        /// </summary>
        internal static string ImportTemperature {
            get {
                return ResourceManager.GetString("ImportTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On Initialisation.
        /// </summary>
        internal static string PowerOnInitialisation {
            get {
                return ResourceManager.GetString("PowerOnInitialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-warning Initialised.
        /// </summary>
        internal static string Prewarninginitialised {
            get {
                return ResourceManager.GetString("Prewarninginitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset 6hr Pre-warning.
        /// </summary>
        internal static string ResetPrewarning {
            get {
                return ResourceManager.GetString("ResetPrewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Offset Adjustment {0} um Ch {1}.
        /// </summary>
        internal static string SensorOffsetAdjustment {
            get {
                return ResourceManager.GetString("SensorOffsetAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Replacement 500 Hours Completed.
        /// </summary>
        internal static string SensorReplacement500HoursCompleted {
            get {
                return ResourceManager.GetString("SensorReplacement500HoursCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Replacement 50 Hours Completed.
        /// </summary>
        internal static string SensorReplacement50HoursCompleted {
            get {
                return ResourceManager.GetString("SensorReplacement50HoursCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Replacement Cancelled.
        /// </summary>
        internal static string SensorReplacementCancelled {
            get {
                return ResourceManager.GetString("SensorReplacementCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Replacement Initiated.
        /// </summary>
        internal static string SensorReplacementInitiated {
            get {
                return ResourceManager.GetString("SensorReplacementInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Status Alarm Mask Off Ch {0}.
        /// </summary>
        internal static string SensorStatusAlarmmaskoffCh {
            get {
                return ResourceManager.GetString("SensorStatusAlarmmaskoffCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Status Alarm mask On Ch {0}.
        /// </summary>
        internal static string SensorStatusAlarmmaskonCh {
            get {
                return ResourceManager.GetString("SensorStatusAlarmmaskonCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Status Disabling Ch {0}.
        /// </summary>
        internal static string SensorStatusDisablingCh {
            get {
                return ResourceManager.GetString("SensorStatusDisablingCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Status Enabling Ch {0}.
        /// </summary>
        internal static string SensorStatusEnablingCh {
            get {
                return ResourceManager.GetString("SensorStatusEnablingCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version Alteration SPU {0} old:{1}, new:{2}.
        /// </summary>
        internal static string SPUUpdate {
            get {
                return ResourceManager.GetString("SPUUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XTS-W2 Rebooted.
        /// </summary>
        internal static string SystemRebooted {
            get {
                return ResourceManager.GetString("SystemRebooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XTS-W2 Started Software Version: {0}.
        /// </summary>
        internal static string SystemStartup {
            get {
                return ResourceManager.GetString("SystemStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIO Error Code: {0}.
        /// </summary>
        internal static string WIOErrorcode {
            get {
                return ResourceManager.GetString("WIOErrorcode", resourceCulture);
            }
        }
    }
}
