//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.gl-group.com/glmm/1.0/", ClrNamespace="schemas.glgroup.com.glmm._1._01")]

namespace schemas.glgroup.com.glmm._1._01
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.gl-group.com/glmm/1.0/")]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private schemas.glgroup.com.glmm._1._01.ServiceErrorCategory ErrorCategoryField;
        
        private string ErrorMessageField;
        
        private string DeveloperDetailsField;
        
        private int PlatformErrorCodeField;
        
        private schemas.glgroup.com.glmm._1._01.ArrayOfString PlatformErrorValuesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public schemas.glgroup.com.glmm._1._01.ServiceErrorCategory ErrorCategory
        {
            get
            {
                return this.ErrorCategoryField;
            }
            set
            {
                this.ErrorCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DeveloperDetails
        {
            get
            {
                return this.DeveloperDetailsField;
            }
            set
            {
                this.DeveloperDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int PlatformErrorCode
        {
            get
            {
                return this.PlatformErrorCodeField;
            }
            set
            {
                this.PlatformErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public schemas.glgroup.com.glmm._1._01.ArrayOfString PlatformErrorValues
        {
            get
            {
                return this.PlatformErrorValuesField;
            }
            set
            {
                this.PlatformErrorValuesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorCategory", Namespace="http://schemas.gl-group.com/glmm/1.0/")]
    public enum ServiceErrorCategory : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConnectionError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAuthenticated = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAuthorized = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://schemas.gl-group.com/glmm/1.0/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.gl-group.com/glmm/1.0/", ConfigurationName="BaseCbmServiceWebServiceSoap")]
public interface BaseCbmServiceWebServiceSoap
{
    
    // CODEGEN: Generating message contract since element name User from namespace http://schemas.gl-group.com/glmm/1.0/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.gl-group.com/glmm/1.0/Login", ReplyAction="*")]
    LoginResponse Login(LoginRequest request);
    
    // CODEGEN: Generating message contract since element name AuthTicket from namespace http://schemas.gl-group.com/glmm/1.0/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.gl-group.com/glmm/1.0/SendOnlineMeasurement", ReplyAction="*")]
    SendOnlineMeasurementResponse SendOnlineMeasurement(SendOnlineMeasurementRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LoginRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://schemas.gl-group.com/glmm/1.0/", Order=0)]
    public LoginRequestBody Body;
    
    public LoginRequest()
    {
    }
    
    public LoginRequest(LoginRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.gl-group.com/glmm/1.0/")]
public partial class LoginRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string User;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string Password;
    
    public LoginRequestBody()
    {
    }
    
    public LoginRequestBody(string User, string Password)
    {
        this.User = User;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LoginResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://schemas.gl-group.com/glmm/1.0/", Order=0)]
    public LoginResponseBody Body;
    
    public LoginResponse()
    {
    }
    
    public LoginResponse(LoginResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.gl-group.com/glmm/1.0/")]
public partial class LoginResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public schemas.glgroup.com.glmm._1._01.ServiceResult LoginResult;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string AuthTicket;
    
    public LoginResponseBody()
    {
    }
    
    public LoginResponseBody(schemas.glgroup.com.glmm._1._01.ServiceResult LoginResult, string AuthTicket)
    {
        this.LoginResult = LoginResult;
        this.AuthTicket = AuthTicket;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SendOnlineMeasurementRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOnlineMeasurement", Namespace="http://schemas.gl-group.com/glmm/1.0/", Order=0)]
    public SendOnlineMeasurementRequestBody Body;
    
    public SendOnlineMeasurementRequest()
    {
    }
    
    public SendOnlineMeasurementRequest(SendOnlineMeasurementRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.gl-group.com/glmm/1.0/")]
public partial class SendOnlineMeasurementRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string AuthTicket;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public byte[] onlineMeasurementReportXmlContent;
    
    public SendOnlineMeasurementRequestBody()
    {
    }
    
    public SendOnlineMeasurementRequestBody(string AuthTicket, byte[] onlineMeasurementReportXmlContent)
    {
        this.AuthTicket = AuthTicket;
        this.onlineMeasurementReportXmlContent = onlineMeasurementReportXmlContent;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SendOnlineMeasurementResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOnlineMeasurementResponse", Namespace="http://schemas.gl-group.com/glmm/1.0/", Order=0)]
    public SendOnlineMeasurementResponseBody Body;
    
    public SendOnlineMeasurementResponse()
    {
    }
    
    public SendOnlineMeasurementResponse(SendOnlineMeasurementResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.gl-group.com/glmm/1.0/")]
public partial class SendOnlineMeasurementResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public schemas.glgroup.com.glmm._1._01.ServiceResult SendOnlineMeasurementResult;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string AuthTicketUpdate;
    
    public SendOnlineMeasurementResponseBody()
    {
    }
    
    public SendOnlineMeasurementResponseBody(schemas.glgroup.com.glmm._1._01.ServiceResult SendOnlineMeasurementResult, string AuthTicketUpdate)
    {
        this.SendOnlineMeasurementResult = SendOnlineMeasurementResult;
        this.AuthTicketUpdate = AuthTicketUpdate;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface BaseCbmServiceWebServiceSoapChannel : BaseCbmServiceWebServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BaseCbmServiceWebServiceSoapClient : System.ServiceModel.ClientBase<BaseCbmServiceWebServiceSoap>, BaseCbmServiceWebServiceSoap
{
    
    public BaseCbmServiceWebServiceSoapClient()
    {
    }
    
    public BaseCbmServiceWebServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BaseCbmServiceWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BaseCbmServiceWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BaseCbmServiceWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LoginResponse BaseCbmServiceWebServiceSoap.Login(LoginRequest request)
    {
        return base.Channel.Login(request);
    }
    
    public schemas.glgroup.com.glmm._1._01.ServiceResult Login(string User, string Password, out string AuthTicket)
    {
        LoginRequest inValue = new LoginRequest();
        inValue.Body = new LoginRequestBody();
        inValue.Body.User = User;
        inValue.Body.Password = Password;
        LoginResponse retVal = ((BaseCbmServiceWebServiceSoap)(this)).Login(inValue);
        AuthTicket = retVal.Body.AuthTicket;
        return retVal.Body.LoginResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SendOnlineMeasurementResponse BaseCbmServiceWebServiceSoap.SendOnlineMeasurement(SendOnlineMeasurementRequest request)
    {
        return base.Channel.SendOnlineMeasurement(request);
    }
    
    public schemas.glgroup.com.glmm._1._01.ServiceResult SendOnlineMeasurement(string AuthTicket, byte[] onlineMeasurementReportXmlContent, out string AuthTicketUpdate)
    {
        SendOnlineMeasurementRequest inValue = new SendOnlineMeasurementRequest();
        inValue.Body = new SendOnlineMeasurementRequestBody();
        inValue.Body.AuthTicket = AuthTicket;
        inValue.Body.onlineMeasurementReportXmlContent = onlineMeasurementReportXmlContent;
        SendOnlineMeasurementResponse retVal = ((BaseCbmServiceWebServiceSoap)(this)).SendOnlineMeasurement(inValue);
        AuthTicketUpdate = retVal.Body.AuthTicketUpdate;
        return retVal.Body.SendOnlineMeasurementResult;
    }
}
