/* 
 * Copyright (C) MPC Data Limited 2012. All rights reserved.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using schemas.glgroup.com.glmm._1._01;
using System.ServiceModel;
using System.IO;

namespace Glmmclient
{
    /// <summary>
    /// This class is used to contact and send data to the GL Machine Measurement Web Service.
    /// It is a wrapper around the code generated by SVCUTIL.
    /// </summary>
    public class GLMMClient : IDisposable
    {
        BaseCbmServiceWebServiceSoapClient client;
        string username;
        string password;
        string authTicket = string.Empty;

        /// <summary>
        /// Constructs a GLMMClient object with the specifced parameters
        /// </summary>
        /// <param name="username">The username to use to connect to the service</param>
        /// <param name="password">The password for the user</param>
        /// <param name="uri">The URI of where the service is located</param>
        public GLMMClient(string username, string password, string uri)
        {
            BasicHttpBinding binding = new BasicHttpBinding();
            Uri uriObj = new Uri(uri);
            if (uriObj.Scheme == Uri.UriSchemeHttps)
            {
                BasicHttpSecurity security = new BasicHttpSecurity();
                security.Mode = BasicHttpSecurityMode.Transport;
                binding.Security = security;
            }

            client = new BaseCbmServiceWebServiceSoapClient(binding, new EndpointAddress(uri));
            this.username = username;
            this.password = password;
        }

        /// <summary>
        /// Logs in to the GL MM Service
        /// </summary>
        /// <exception cref="InvalidOperationException">Thrown if the client is not connected to the web service or a unknown error occurs</exception>
        /// <exception cref="UnauthorizedAccessException">Thrown if the user is not authorized to perform the send operation</exception>
        /// <exception cref="IOException">Thrown if a connection cannot be made to the service.</exception>
        public void Login()
        {
            ServiceResult result;

            result = this.client.Login(this.username, this.password, out this.authTicket);

            if (!result.Success)
            {
                //An error occured, work out what it is
                //and throw an exception
                switch (result.ErrorCategory)
                {
                    case ServiceErrorCategory.NotAuthenticated:
                        throw new InvalidOperationException("Not connected to Web Service");
                    case ServiceErrorCategory.NotAuthorized:
                        throw new UnauthorizedAccessException(result.ErrorMessage);
                    case ServiceErrorCategory.Other:
                        throw new InvalidOperationException(result.ErrorMessage);
                    case ServiceErrorCategory.ConnectionError:
                        throw new System.IO.IOException(result.ErrorMessage);
                    case ServiceErrorCategory.None:
                    default:
                        //Do Nothing
                        break;
                }
            }
        }

        /// <summary>
        /// Sends a measurement 
        /// </summary>
        /// <param name="measurementFile">The name of the file that holds XML document that contains the data to send to the GL Machine Measurement Web Service</param>
        /// <exception cref="InvalidOperationException">Thrown if the client is not connected to the web service or a unknown error occurs</exception>
        /// <exception cref="UnauthorizedAccessException">Thrown if the user is not authorized to perform the send operation</exception>
        /// <exception cref="IOException">Thrown if a connection cannot be made to the service.</exception>
        public void SendMeasurement(string measurementFile)
        {
            ServiceResult result;
            string updateTicket;
            byte[] buffer = null;

            if (this.authTicket == string.Empty)
            {
                throw new InvalidOperationException("Not connected to Web Service");
            }

            using (BinaryReader reader = new BinaryReader(File.Open(measurementFile, FileMode.Open)))
            {
                int length = (int)reader.BaseStream.Length;
                buffer = reader.ReadBytes(length);
            }

            result = this.client.SendOnlineMeasurement(this.authTicket, buffer, out updateTicket);

            if (!result.Success)
            {
                //An error occured, work out what it is
                //and throw an exception
                switch (result.ErrorCategory)
                {
                    case ServiceErrorCategory.NotAuthenticated:
                        throw new InvalidOperationException("Not connected to Web Service");
                    case ServiceErrorCategory.NotAuthorized:
                        throw new UnauthorizedAccessException(result.ErrorMessage);
                    case ServiceErrorCategory.Other:
                        throw new InvalidOperationException(result.ErrorMessage);
                    case ServiceErrorCategory.ConnectionError:
                        throw new System.IO.IOException(result.ErrorMessage);
                    case ServiceErrorCategory.None:
                    default:
                        //Do Nothing
                        break;
                }
            }
        }

        /// <summary>
        /// Finalizer to catch no disposed clients
        /// </summary>
        ~GLMMClient()
        {
            Dispose(false);
        }

        /// <summary>
        /// Dipose method called to clean up the client when it
        /// has been finished being used.
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Internal dispose method for use by the class
        /// </summary>
        /// <param name="disposing"></param>
        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.client.Close();
                this.client = null;
            }
        }
    }
}
