/* 
 * Copyright (C) MPC Data Limited 2012. All rights reserved.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Diagnostics;
using System.Timers;
using log4net;
using HelperClasses;
using System.Diagnostics.CodeAnalysis;
using DataCollectionSDK;

namespace Framework
{
    /// <summary>
    /// Class responsible for creating and maintaining threads concerning scheduled logging and running of a part
    /// </summary>
    class ScheduledTask : IDisposable
    {
        /// <summary>
        /// The external interface component
        /// </summary>
        private IExtInterface part;

        /// <summary>
        /// Timer object that calls the scheduled task Run method
        /// </summary>
        private System.Timers.Timer runTimer = null;

        /// <summary>
        /// Timer object that calls the scheduled task Log method
        /// </summary>
        private System.Timers.Timer logTimer = null;

        /// <summary>
        /// Logging
        /// </summary>
        private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        /// <summary>
        /// Set up access to external plugins 
        /// </summary>
        /// <param name="part"></param>
        public ScheduledTask(IExtInterface part)
        {
            this.part = part;

            if (this.part.RunSchedule != 0)
            {
                runTimer = new System.Timers.Timer();
                runTimer.Interval = this.part.RunSchedule;
                runTimer.Elapsed += new ElapsedEventHandler(OnRunElapsed);
                runTimer.AutoReset = false;
                runTimer.Start();
            }

            if (this.part.LogSchedule != 0)
            {
                logTimer = new System.Timers.Timer();
                logTimer.Interval = this.part.LogSchedule;
                logTimer.Elapsed += new ElapsedEventHandler(OnLogElapsed);
                logTimer.AutoReset = false;
                logTimer.Start();
            }
        }

        /// <summary>
        /// Called when the timer has elapsed by the run interval specified by the extension
        /// </summary>
        /// <param name="sender">The timer that sent the event</param>
        /// <param name="evnt">The event generated by the timer</param>
        [SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes")]
        void OnRunElapsed(object sender, ElapsedEventArgs evnt)
        {
            runTimer.Stop();

            Stopwatch stopWatch = Stopwatch.StartNew();

            try
            {
                this.part.Run();
            }
            catch (Exception e)
            {
                logger.ErrorFormat("Exception for '{0}': {1}", this.part.GetType().ToString(), e.ToString());
            }

            stopWatch.Stop();
            long nextScheduleTime = (this.part.RunSchedule - stopWatch.ElapsedMilliseconds);

            if (nextScheduleTime <= 0)
            {
                nextScheduleTime = 1;
            }

            if (this.part.Realtime)
            {
                logger.InfoFormat("Realtime Task {2} took {0} ms to execute.  It will execute again in {1} ms", stopWatch.ElapsedMilliseconds, nextScheduleTime, this.part.GetType().Name);
                runTimer.Interval = nextScheduleTime;                
            }
            else
            {
                runTimer.Interval = this.part.RunSchedule;
            }

            runTimer.Start();
        }

        /// <summary>
        /// Method called by the the log timer to log data to the database
        /// </summary>
        /// <param name="sender">The timer that sent the event</param>
        /// <param name="evnt">The event generated by the timer</param>
        [SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes")]
        void OnLogElapsed(object sender, ElapsedEventArgs evnt)
        {
            logTimer.Stop();
            DateTime logTime = DateTime.UtcNow;

            Stopwatch stopWatch = Stopwatch.StartNew();
            
            try
            {
                this.part.Log(logTime);
            }
            catch (Exception e)
            {
                logger.InfoFormat("OnElapsed.Log: Exception for '{0}': {1}", this.part.GetType().ToString(), e.ToString());
            }

            stopWatch.Stop();
            long nextScheduleTime = (this.part.LogSchedule - stopWatch.ElapsedMilliseconds);

            if (nextScheduleTime <= 0)
            {
                nextScheduleTime = 1;
            }

            logger.InfoFormat("Log {2} took {0} ms to execute.  It will execute again in {1} ms", stopWatch.ElapsedMilliseconds, nextScheduleTime, this.part.GetType().Name);
            logTimer.Interval = nextScheduleTime;

            logTimer.Start();
        }


        /// <summary>
        /// Stops a task from being run.
        /// </summary>
        public void Stop()
        {
            this.part.Stop();

            if (runTimer != null)
            {
                runTimer.Stop();
                runTimer.Enabled = false;
                runTimer.Elapsed -= new ElapsedEventHandler(OnRunElapsed);
            }

            if (logTimer != null)
            {
                logTimer.Stop();
                logTimer.Enabled = false;
                logTimer.Elapsed -= new ElapsedEventHandler(OnLogElapsed);
            }

        }

        #region IDisposable Members

        /// <summary>
        /// Finalizer for Disposing correctly from
        /// the GC.
        /// </summary>
        ~ScheduledTask()
        {
            Dispose(false);
        }

        /// <summary>
        /// Internal function for handling Dispose being called from Finalizer or Dispose
        /// </summary>
        /// <param name="freeManagedObjectsAlso"></param>
        protected virtual void Dispose(bool freeManagedObjectsAlso)
        {
            if (freeManagedObjectsAlso)
            {
                this.runTimer.Dispose();
                this.runTimer = null;

                this.logTimer.Dispose();
                this.logTimer = null;
            }
        }

        /// <summary>
        /// Dispose method for cleaning up timer
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        #endregion

    }

}
