#!/usr/bin/env python3
"""
spec_matrix.py — auto-generate spec→test coverage from @spec tags.

Walks host/test/ for `@spec X.Y §N.M.K` and `@vendor-extension <name>`
comments, then cross-references against host/specs/feature_matrix.csv
to produce a coverage report.

Exits with non-zero status if any spec ID in feature_matrix.csv has
zero corresponding tests — useful as a CI gate.

Usage:
    cd host
    python3 tools/spec_matrix.py [--check] [--out coverage_matrix.md]

  --check      exit non-zero if coverage < 100% (for CI)
  --out FILE   write the coverage matrix markdown to FILE
"""

import argparse
import csv
import re
import sys
from pathlib import Path
from collections import defaultdict


SPEC_TAG_RE = re.compile(r'@spec\s+(\d+\.\d+)\s+§([\d\.]+(?:\.\d+)*)')
VENDOR_TAG_RE = re.compile(r'@vendor-extension\s+([\w-]+)')


def find_test_files(test_dir: Path):
    return sorted(p for p in test_dir.rglob("test_*.c"))


def find_src_files(src_dir: Path):
    return sorted(p for p in src_dir.rglob("*.c") if "third_party" not in str(p))


def collect_spec_tags(file_path: Path):
    """Return list of (spec_version, section, line_no) for @spec tags."""
    tags = []
    try:
        with file_path.open() as f:
            for lineno, line in enumerate(f, 1):
                for m in SPEC_TAG_RE.finditer(line):
                    tags.append((m.group(1), m.group(2), lineno))
    except (OSError, UnicodeDecodeError):
        pass
    return tags


def collect_vendor_tags(file_path: Path):
    tags = []
    try:
        with file_path.open() as f:
            for lineno, line in enumerate(f, 1):
                for m in VENDOR_TAG_RE.finditer(line):
                    tags.append((m.group(1), lineno))
    except (OSError, UnicodeDecodeError):
        pass
    return tags


def load_feature_matrix(csv_path: Path):
    """Load feature_matrix.csv as list of dicts, robustly to varying header sets."""
    if not csv_path.exists():
        return []
    rows = []
    with csv_path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def build_coverage_report(test_dir, src_dir, feature_csv):
    """Return (markdown_string, num_uncovered)."""
    test_files = find_test_files(test_dir)
    src_files = find_src_files(src_dir)

    # Map: spec_version → {section → [(file, line)]}
    spec_in_tests = defaultdict(lambda: defaultdict(list))
    spec_in_src   = defaultdict(lambda: defaultdict(list))
    vendor_in_tests = defaultdict(list)
    vendor_in_src   = defaultdict(list)

    for f in test_files:
        for v, sec, ln in collect_spec_tags(f):
            spec_in_tests[v][sec].append((f.name, ln))
        for name, ln in collect_vendor_tags(f):
            vendor_in_tests[name].append((f.name, ln))

    for f in src_files:
        for v, sec, ln in collect_spec_tags(f):
            spec_in_src[v][sec].append((str(f.relative_to(src_dir.parent)), ln))
        for name, ln in collect_vendor_tags(f):
            vendor_in_src[name].append((str(f.relative_to(src_dir.parent)), ln))

    feature_rows = load_feature_matrix(feature_csv)

    out = ["# Auto-Generated Spec Coverage Matrix\n"]
    out.append(f"_Generated by spec_matrix.py from `host/test/` and `src/` tree._\n")
    out.append("\n## Summary\n")

    total_test_tags = sum(len(secs) for secs in spec_in_tests.values())
    total_src_tags = sum(len(secs) for secs in spec_in_src.values())
    out.append(f"- Spec tags in test files: **{total_test_tags}** unique sections\n")
    out.append(f"- Spec tags in src/ files: **{total_src_tags}** unique sections\n")
    out.append(f"- Vendor extensions in tests: **{len(vendor_in_tests)}**\n")
    out.append(f"- Vendor extensions in src: **{len(vendor_in_src)}**\n")

    out.append("\n## Coverage by Spec Version\n")
    for version in sorted(spec_in_tests.keys() | spec_in_src.keys()):
        out.append(f"\n### Spec {version}\n\n")
        out.append("| Section | Tests | Src |\n|---|---|---|\n")
        sections = sorted(set(spec_in_tests[version].keys()) | set(spec_in_src[version].keys()),
                          key=lambda s: tuple(int(p) for p in s.split('.') if p.isdigit()))
        for sec in sections:
            tests = spec_in_tests[version].get(sec, [])
            srcs = spec_in_src[version].get(sec, [])
            t_str = "; ".join(f"{f}:{ln}" for f, ln in tests[:3]) + (f" (+{len(tests)-3} more)" if len(tests) > 3 else "")
            s_str = "; ".join(f"{f}:{ln}" for f, ln in srcs[:3]) + (f" (+{len(srcs)-3} more)" if len(srcs) > 3 else "")
            out.append(f"| §{sec} | {t_str or '_none_'} | {s_str or '_none_'} |\n")

    if vendor_in_tests or vendor_in_src:
        out.append("\n## Vendor Extensions\n\n")
        out.append("| Extension | Tests | Src |\n|---|---|---|\n")
        for name in sorted(set(vendor_in_tests.keys()) | set(vendor_in_src.keys())):
            tests = vendor_in_tests.get(name, [])
            srcs = vendor_in_src.get(name, [])
            t_str = "; ".join(f"{f}:{ln}" for f, ln in tests[:3])
            s_str = "; ".join(f"{f}:{ln}" for f, ln in srcs[:3])
            out.append(f"| {name} | {t_str or '_none_'} | {s_str or '_none_'} |\n")

    # Coverage check against feature_matrix.csv if present.
    #
    # A req_id like "R-§4.2-NEW" or "R-§2.1-4" is considered covered if EITHER:
    #   (a) the literal req_id text appears in any test file, OR
    #   (b) the req_id's spec section has at least one @spec tag in tests.
    # The section is extracted as the chars between the "§" and the next "-"
    # (or end-of-string). Examples: R-§4.2-NEW → "4.2"; R-§AppE → "AppE".
    uncovered = []
    weakly_covered = []  # covered by section, not by exact req_id match
    if feature_rows:
        out.append("\n## Coverage Check Against feature_matrix.csv\n")

        # Flatten test sections to a set: ("8.5", "4.4"), ("8.7", "4.4"), ...
        all_test_sections = set()
        for v, sections in spec_in_tests.items():
            for sec in sections:
                all_test_sections.add(sec)
                # Also count parent sections: a tag "§4.4.1" covers "§4.4".
                parts = sec.split('.')
                for i in range(1, len(parts)):
                    all_test_sections.add('.'.join(parts[:i]))

        # Pre-read test files once.
        test_blobs = []
        for f in test_files:
            try:
                test_blobs.append(f.read_text())
            except (OSError, UnicodeDecodeError):
                pass

        for row in feature_rows:
            req_id = row.get('req_id', '')
            if not req_id:
                continue

            # (a) literal match
            literal_hit = any(req_id in blob for blob in test_blobs)
            if literal_hit:
                continue

            # (b) section match — extract section between "§" and next "-".
            m = re.match(r'R-§([^-]+)', req_id)
            section_id = m.group(1) if m else None
            if section_id and section_id in all_test_sections:
                weakly_covered.append((req_id, section_id))
                continue

            uncovered.append(req_id)

        if uncovered:
            out.append(f"\n**Missing tests** for {len(uncovered)} requirement(s):\n")
            for req in uncovered[:10]:
                out.append(f"- {req}\n")
            if len(uncovered) > 10:
                out.append(f"- ...and {len(uncovered) - 10} more\n")
        if weakly_covered:
            out.append(f"\n**Section-only coverage** for {len(weakly_covered)} requirement(s) "
                       "(test exists for the section, but req_id not cited verbatim):\n")
            for req, sec in weakly_covered[:5]:
                out.append(f"- {req} (matches section §{sec})\n")
            if len(weakly_covered) > 5:
                out.append(f"- ...and {len(weakly_covered) - 5} more\n")
        if not uncovered and not weakly_covered:
            out.append("\nAll feature_matrix.csv requirements have direct test coverage.\n")
        elif not uncovered:
            out.append("\n**All requirements covered** (some only at section granularity).\n")

    return "".join(out), len(uncovered)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if any spec ID has no coverage")
    parser.add_argument("--out", default="coverage_matrix.md",
                        help="output markdown file (default: coverage_matrix.md)")
    args = parser.parse_args()

    here = Path(__file__).resolve().parent.parent  # host/
    test_dir = here / "test"
    src_dir = here.parent / "src"
    feature_csv = here / "specs" / "feature_matrix.csv"

    if not test_dir.exists() or not src_dir.exists():
        print(f"ERROR: test_dir={test_dir} or src_dir={src_dir} not found", file=sys.stderr)
        return 2

    report, uncovered = build_coverage_report(test_dir, src_dir, feature_csv)
    out_path = here / args.out
    out_path.write_text(report)
    print(f"Wrote {out_path}")
    if args.check and uncovered > 0:
        print(f"FAIL: {uncovered} requirement(s) without coverage", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
