using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;
using WebServiceObjects;

namespace ConfigurationWebsite.Models
{
    public class EngineRunTimeModel
    {
        /// <summary>
        /// The key that is generated that should be sent to AMOT
        /// </summary>
        public uint  CurrentEngineRunTime { get; set; }

        /// <summary>
        /// The Key that is generated by AMOT in repsonse
        /// to the Challenge key
        /// </summary>
        [Required]
        public uint NewEngineRunTime { get; set; }

        /// <summary>
        /// A string holding the status of the user password reset
        /// This will be null, password reset or invalid key
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Flag indicating if the user can set the runtime
        /// </summary>
        public bool CanSave {set; get;}
    }
}