using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;
using WebServiceObjects;
namespace ConfigurationWebsite.Models
{
    public class UserReset
    {
        /// <summary>
        /// The key that is generated that should be sent to AMOT
        /// </summary>
        public string ChallengeKey { get; set; }

        /// <summary>
        /// The Key that is generated by AMOT in repsonse
        /// to the Challenge key
        /// </summary>
        public string ResponseKey { get; set; }

        /// <summary>
        /// A string holding the status of the user password reset
        /// This will be null, password reset or invalid key
        /// </summary>
        public string Status { get; set; }
    }
}